In [25]:
import numpy as np

In [26]:
# a simple array
a = np.array([0,1,2,3,4,5])
a

array([0, 1, 2, 3, 4, 5])

In [27]:
a.ndim #num of dimensions 


1

In [28]:
a.shape #shape of the array

(6,)

In [29]:
#let's reshape the array into 3 rows and 2 cols
b = a.reshape(3,2)

In [30]:
b.ndim

2

In [31]:
b.shape

(3, 2)

In [32]:
a.shape #shape of a is still the same.

(6,)

In [33]:
b[1][0] = 77
b


array([[ 0,  1],
       [77,  3],
       [ 4,  5]])

In [34]:
a #Though shape does not change, b is still a copy of a hence change of element in b is reflected in a.

array([ 0,  1, 77,  3,  4,  5])

In [35]:
c = a.reshape(3,2).copy() # copy will make a copy.
c.shape

(3, 2)

In [36]:
c[1][0] = 99 #so any change done here is not reflected on a unlike b.
c


array([[ 0,  1],
       [99,  3],
       [ 4,  5]])

In [37]:
a

array([ 0,  1, 77,  3,  4,  5])

In [38]:
a*2 #All elements multiplied.


array([  0,   2, 154,   6,   8,  10])

In [39]:
a**2 # power

array([   0,    1, 5929,    9,   16,   25])

In [40]:
a[np.array([2,3])]  # np.array used as index.


array([77,  3])

In [41]:
a > 4 # returns a bool array satisfying the condition here ' a > 4'

array([False, False,  True, False, False,  True], dtype=bool)

In [43]:
a[a>4] = 4  # change elements to 4 which are greater than 4.
a


array([0, 1, 4, 3, 4, 4])

In [47]:
a.clip(2,5) # change values so that they lie between this interval.

array([2, 2, 4, 3, 4, 4])

In [48]:
#use isnan to check if element is not a real number.

c = np.array([1,2,np.NAN,4])
np.isnan(c)


array([False, False,  True, False], dtype=bool)

In [49]:
c[~np.isnan(c)]


array([ 1.,  2.,  4.])

In [51]:
np.mean(c[~np.isnan(c)])

2.3333333333333335

In [52]:
c.dtype #data type of the array.

dtype('float64')